modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lead"
version = "${version}"
displayName = "Lead"
authors = "Kall"
description = '''
'''
#logoFile = ""